services:
  frontend:
    image: othelloengineer/kubekata-level-frontend:0.1.5-19
    ports:
      - "8080:5173"
    environment:
      - CURLPOD=curlpod:8080
  curlpod:
    image: othelloengineer/curl-pod:0.0.7
    ports:
      - "8081:8080"
  cluster-observer:
    image: othelloengineer/kubekata-cluster-observer:0.0.8
    ports:
      - "8082:8080"
