services:
  frontend:
    image: othelloengineer/kubekata-level-frontend:0.2.2
    ports:
      - "8080:5173"
    environment:
      - CURLPOD=curlpod:8080
      - VITE_USE_CLUSTER=true
      - VITE_CURLPOD_URL=http://curlpod
      - VITE_CURLPOD_PORT=8080
      - VITE_CLUSTER_OBSERVER_URL=http://cluster-observer
      - VITE_CLUSTER_OBSERVER_PORT=8081
    depends_on:
      - curlpod
      - cluster-observer
  curlpod:
    image: othelloengineer/curl-pod:0.0.7
    ports:
      - "8081:8080"
  cluster-observer:
    image: othelloengineer/kubekata-cluster-observer:0.2.2
    ports:
      - "8082:8081"
