apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    kube: kata
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: othelloengineer/hello-go:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MESSAGE
          value: "Hello, World!"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /test-volume
          name: test-volume
      volumes:
      - name: test-volume
        emptyDir: {}
