apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-observer
  annotations:
    container.apparmor.security.beta.kubernetes.io/cluster-observer: unconfined
spec:
  selector:
    matchLabels:
      app: cluster-observer
  template:
    metadata:
      labels:
        app: cluster-observer
    spec:
      volumes:
      - name: cluster-observer
        emptyDir: {}
      containers:
      - name: cluster-observer
        image: othelloengineer/kubekata-cluster-observer:0.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: cluster-observer
          mountPath: root/mounts/shared-volume
      - name: hello-go
        image: othelloengineer/hello-go:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cluster-observer
          mountPath: root/mounts/other-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curlpod
spec:
  selector:
    matchLabels:
      app: curlpod
  template:
    metadata:
      labels:
        app: curlpod
    spec:
      containers:
      - name: curlpod
        image: othelloengineer/curl-pod:0.0.7
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: othelloengineer/kubekata-level-frontend:0.3.0
        imagePullPolicy: Always
        env:
        - name: CURLPOD
          value: curlpod:8080
        - name: VITE_USE_CLUSTER
          value: "true"
        - name: VITE_CURLPOD_URL
          value: http://curlpod
        - name: VITE_CURLPOD_PORT
          value: "8080"
        - name: VITE_CLUSTER_OBSERVER_URL
          value: http://cluster-observer
        - name: VITE_CLUSTER_OBSERVER_PORT
          value: "8080"
        ports:
        - containerPort: 5137

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-observer
spec:
  selector:
    app: cluster-observer
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: curlpod
spec:
  selector:
    app: curlpod
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - nodePort: 31427
    port: 5173
    protocol: TCP
    targetPort: 5173