apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-observer
  annotations:
    container.apparmor.security.beta.kubernetes.io/cluster-observer: unconfined
spec:
  selector:
    matchLabels:
      app: cluster-observer
  template:
    metadata:
      labels:
        app: cluster-observer
    spec:
      volumes:
      - name: cluster-observer
        emptyDir: {}
      containers:
      - name: cluster-observer
        image: othelloengineer/kubekata-cluster-observer:0.2.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cluster-observer
          mountPath: root/mounts/shared-volume
      - name: nginx
        image: nginx:1.19.6
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cluster-observer
          mountPath: root/mounts/other-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curlpod
spec:
  selector:
    matchLabels:
      app: curlpod
  template:
    metadata:
      labels:
        app: curlpod
    spec:
      containers:
      - name: curlpod
        image: othelloengineer/curl-pod:0.0.7
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: othelloengineer/kubekata-level-frontend:0.2.2
        resources:
        ports:
        - containerPort: 5137

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-observer
spec:
  selector:
    app: cluster-observer
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: curlpod
spec:
  selector:
    app: curlpod
  ports:
  - port: 8080
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 5137
    targetPort: 5137