apiVersion: v1
kind: Service
metadata:
  name: access-a-pod
spec:
  type: NodePort
  selector:
    app: configure-a-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
